import React, { useState } from 'react';
import { ShieldCheck, ShieldAlert, AlertTriangle, Copy, Check } from 'lucide-react';

export default function ActionRecommendations({ result, emailData }) {
  const [copied, setCopied] = useState(false);
  const { verdict, recommendations = [] } = result;

  const generateReportText = () => {
    return `=== EMAIL THREAT INCIDENT REPORT ===
Date: ${new Date().toISOString()}
Verdict: ${(result.verdictTitle || verdict).toUpperCase()}
Risk Score: ${result.score}%
Model Certainty: ${result.confidence}%

--- SENDER ENVELOPE ---
From: ${emailData.senderName || 'N/A'} <${emailData.senderEmail || 'N/A'}>
Subject: ${emailData.subject || 'N/A'}

--- IDENTIFIED RED FLAGS ---
${(result.redFlags || []).map((f, i) => `${i + 1}. [${f.severity.toUpperCase()}] ${f.title}: ${f.description}`).join('\n')}

--- RECOMMENDED INCIDENT ACTIONS ---
${recommendations.map((r, i) => `${i + 1}. ${r.title} - ${r.details}`).join('\n')}

Generated by Zero-Day PhishShield Enterprise
`;
  };

  const handleCopyReport = () => {
    navigator.clipboard.writeText(generateReportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 transition-colors duration-150">
      <div className="bg-slate-50 dark:bg-slate-950/60 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm">
        <div className="flex items-center justify-between mb-4 pb-3 border-b border-slate-200 dark:border-slate-800">
          <div className="flex items-center space-x-2">
            {verdict === 'phishing' ? (
              <ShieldAlert className="w-4 h-4 text-rose-500" />
            ) : verdict === 'suspicious' ? (
              <AlertTriangle className="w-4 h-4 text-amber-500" />
            ) : (
              <ShieldCheck className="w-4 h-4 text-emerald-500" />
            )}
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-800 dark:text-slate-200">
              Recommended Security Response Playbook
            </h4>
          </div>

          <button
            onClick={handleCopyReport}
            className="flex items-center space-x-1.5 px-3 py-1.5 rounded-lg bg-white dark:bg-slate-900 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white text-xs font-medium border border-slate-200 dark:border-slate-800 transition-colors shadow-sm"
          >
            {copied ? (
              <>
                <Check className="w-3.5 h-3.5 text-emerald-500" />
                <span className="text-emerald-600 dark:text-emerald-400 font-semibold">Copied to Clipboard</span>
              </>
            ) : (
              <>
                <Copy className="w-3.5 h-3.5 text-slate-400" />
                <span>Copy Summary</span>
              </>
            )}
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {recommendations.map((rec, idx) => (
            <div
              key={idx}
              className="p-4 rounded-lg bg-white dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800/80 flex items-start space-x-3 shadow-sm"
            >
              <div className="w-5 h-5 rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-mono text-xs font-semibold flex items-center justify-center shrink-0 mt-0.5">
                {idx + 1}
              </div>
              <div>
                <h5 className="text-xs font-semibold text-slate-900 dark:text-slate-200">
                  {rec.title}
                </h5>
                <p className="text-xs text-slate-600 dark:text-slate-400 mt-1 leading-relaxed">
                  {rec.details}
                </p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
